name: chessbi
version: '1.0.0'
config-version: 2

profile: chessbi

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  chessbi:
    staging:
      +materialized: view
    marts:
      +materialized: table
